package uncc.ssdi.dao;

import java.util.Iterator;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.springframework.beans.factory.annotation.Autowired;

import uncc.ssdi.model.IProduct;
import uncc.ssdi.model.Product;
import uncc.ssdi.utilities.*;


public class ProductDao implements IProductDao {
	
/*	@Autowired
	private SessionFactory factory;
	
	
	public SessionFactory getFactory() {
		return factory;
	}
	public void setFactory(SessionFactory factory) {
		this.factory = factory;
	}
	
	Session session = factory.openSession();
	
	Transaction tx = null;
	@Override
	public List<IProduct> getProducts() {
		tx = session.beginTransaction();
		String hql = "FROM PRODUCTS";
		List products = session.createQuery(hql).list();
		//List products = query.list();
		for (Iterator iterator = products.iterator(); iterator.hasNext();){
            IProduct product = (Product) iterator.next(); 
            System.out.print("Product Name: " + product.getName()); 
            System.out.print("  Description: " + product.getDescription()); 
            System.out.println("  Base Price: " + product.getBasePrice()); 
         }
		return products;
	}*/
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ProductRepository ProductRepository;
	public Iterable<Product> getAllProducts() {
		// This returns a JSON or XML with the users
		return ProductRepository.findAll();
	}
	
}
